### ISSUE TITLE
苹果版本9.2(13c75)浏览器下只有一列

### ISSUE THREAD

**Issue by ALiangTech** [heikaimu/vue-waterfall-plugin#2]
在waterfall.vue中const cols = Math.max(Math.floor((gridWidth - gutter) / gridItemWidth), 1);这个会取值为1相同屏幕尺寸 一个有俩列 一个只有一列

**Comment by heikaimu** [comment]
什么浏览器呢

**Comment by HuDaHei** [comment]
safari浏览器
