### ISSUE TITLE
页面使用多个组件出现异常

### ISSUE THREAD

**Issue by weixisheng** [heikaimu/vue-waterfall-plugin#21]
1.一个页面使用了n个子组件，这个数量是动态的，根据接口配置
2.子组件使用了瀑布流组件做布局，会出现部分子组件高度坍塌
![image](https://user-images.githubusercontent.com/16042305/111602573-72179580-880e-11eb-9791-b1d8c0b7b776.png)

**Comment by heikaimu** [comment]
你可以转变下思路，用一个瀑布流组件，然后根据接口数据修改组件的配置还有卡片样式。&nbsp;



Pansy|&nbsp;HR

T:18508285872
Q:825263041&nbsp; &nbsp; &nbsp; &nbsp;

&nbsp;&nbsp;&nbsp;



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午5:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [heikaimu/vue-waterfall-plugin] 页面使用多个组件出现异常 (#21)





 
1.一个页面使用了n个子组件，这个数量是动态的，根据接口配置
 2.子组件使用了瀑布流组件做布局，会出现部分子组件高度坍塌

**Comment by weixisheng** [comment]
![image](https://user-images.githubusercontent.com/16042305/111604021-dbe46f00-880f-11eb-8bab-2a2b3625767e.png)
除了瀑布流之外的布局，有很多情况，不好放在瀑布流组件里面-_-
