### ISSUE TITLE
页面纵向一开始是堆叠在一起的 transitonY是没有生效

### ISSUE THREAD

**Issue by XYH1996** [heikaimu/vue-waterfall-plugin#5]
我是f12用调试工具模拟移动端预览页面，出现这个问题，当我退出f12全屏，又重新进入f12，相当于重新计算一次，此时则正常

**Comment by milaotou** [comment]
怎么解决呢？

**Comment by cwzp990** [comment]
我也遇到这种情况了...调试源码发现是由于图片加载慢时计算高度错误![Uploading image.png…]()
