### ISSUE TITLE
提几点建议

### ISSUE THREAD

**Issue by rieval** [heikaimu/vue-waterfall-plugin#8]
* 增加一个等高的显示方案
* 在有充足的数据前提下，预先设置 `img` 的 `div` 父组件的宽高为 `img` 的宽高，`background-color` 属性设置为 `img` 目标图像的主色调，像 Twitter 那样，在图片还没加载完成时能获得一个较好的体验。

可以的话希望能考虑一下。

谢谢

**Comment by heikaimu** [comment]
等高是啥意思。

**Comment by rieval** [comment]
![img](https://i.loli.net/2020/05/08/sKhM2HgViuSf6Od.jpg)

类似于这种？每一行图片高度是相同的，宽度自适应，然后列个数也会有所不同。

（这种需求可能比较少，您觉得不必要的话无视即可）

倒是第二点我希望您能考虑一下，因为我个人觉得这种体验真的很好。

一些图片懒加载方式也会先渲染一个 placeholder 框架以防止图片突然蹦出将后面的内容挤到下面去（屏幕外），主色调的话也能增强一些用户体验，取不到主色调就统一用同一个色号渲染 placeholder 也不失为一个折中办法。

**Comment by heikaimu** [comment]
我现在提供的是一个比较纯粹的盒子，基本上不带任何样式，你说的颜色填充也只可能是填充整块，但是可能有些人只想要填充图片这一块，其实现在也可以实现你说的第二点，我刚才实验了一下，比较简单，你可以直接就把高度、颜色信息写在你的img里面，然后图片加载完的load事件直接把高度设置成auto就行了
```
<img
    :src="props.data.src"
    :style="{
         height: props.data.height,
         backgroundColor: props.data.backgroundColor
     }"
     @load="load(props.data)"
 >
```
```
methods: {
  load(row) {
      row.height = 'auto';
      this.$refs.waterfall.refresh();
    }
}
```

**Comment by rieval** [comment]
您说的对，我的意思也是只填充图片这一块。因为我修改了一些样式，父 `div` 下只有 `img` 标签，我先入为主想着填充父 `div` 的背景颜色也是一样的。

您的方法我刚尝试了一下，发现了一个问题，就是我设置（获取）的 `height` 只是图片原本大小时的高度，但渲染完成后的 `height: auto` 是根据固定值 `width` 计算出来的，然后就会出现这种状况：

![img](https://i.loli.net/2020/05/08/DKMjlXzi7kYq315.jpg)

在图像加载后还是会发生抖动。

您的意思是我设置的 `height` 不应该是原图像的高而是经过（ `width` / 图像原宽度 * 图像原高度）这样计算出来的高度吗？

**Comment by heikaimu** [comment]
改版了，你可以看下

**Comment by lhd-1727865856** [comment]
我手机端，用computed计算出来的数据为什么不会渲染呢
